name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - alpha
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Install node modules
        run: |
          npm install

      - name: Run test
        run: |
          npm run test:cov
          env:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - name: Upload Jest JUnit test results
        uses: actions/upload-artifact@v3
        with:
            name: jest-test-results
            path: ./reports/junit/junit.xml